import assert from 'node:assert/strict';
const base='http://localhost:3000';
const day='2001-01-02';
const headers={'Content-Type':'application/json',Cookie:'',Origin:base};
const get=async()=>{const res=await fetch(`${base}/api/entries`,{headers});assert.equal(res.status,200,await res.clone().text());return(await res.json()).entries;};
let wrote=false;
try{
 const anonymous=await fetch(`${base}/api/entries`);assert.equal(anonymous.status,401);
 const wrongPassword=await fetch(`${base}/api/session`,{method:'POST',headers,body:JSON.stringify({password:'wrong-password'})});assert.equal(wrongPassword.status,401,await wrongPassword.clone().text());
 const login=await fetch(`${base}/api/session`,{method:'POST',headers,body:JSON.stringify({password:'local-diary-test-password'})});assert.equal(login.status,200,await login.clone().text());
 const cookie=login.headers.get('set-cookie');assert.ok(cookie.includes('HttpOnly'));assert.ok(cookie.includes('SameSite=Strict'));headers.Cookie=cookie.split(';')[0];
 const page=await fetch(`${base}/`,{headers});assert.equal(page.status,200);
 const forged=await fetch(`${base}/api/entries`,{headers:{Cookie:'clear_day_session=1234.forged'}});assert.equal(forged.status,401);
 const before=await get();assert.ok(!before.some(e=>e.day===day),'Test date already occupied; refusing to overwrite.');
 const bad=await fetch(`${base}/api/entries`,{method:'PUT',headers,body:JSON.stringify({day,clarity:8})});assert.equal(bad.status,400);
 const cross=await fetch(`${base}/api/entries`,{method:'PUT',headers:{...headers,Origin:'https://other.invalid'},body:JSON.stringify({day,clarity:3})});assert.equal(cross.status,403);
 const saved=await fetch(`${base}/api/entries`,{method:'PUT',headers,body:JSON.stringify({day,clarity:3,sleepTime:'23:30',wakeTime:'08:00',exerciseMinutes:0,coffeeCups:0})});assert.equal(saved.status,200,await saved.clone().text());wrote=true;
 const first=await get();assert.equal(first.length,before.length+1);assert.equal(first.find(e=>e.day===day).exerciseMinutes,0);
 const updated=await fetch(`${base}/api/entries`,{method:'PUT',headers,body:JSON.stringify({day,clarity:4,exerciseMinutes:20})});assert.equal(updated.status,200);
 const second=await get();assert.equal(second.length,before.length+1);assert.equal(second.find(e=>e.day===day).clarity,4);assert.equal(second.find(e=>e.day===day).sleepTime,null);
 assert.equal(second.find(e=>e.day===day).napMinutes,null);
 const withNap={...second.find(e=>e.day===day),napMinutes:25,napStartTime:'14:10',napFeeling:3};
 const napSaved=await fetch(`${base}/api/entries`,{method:'PUT',headers,body:JSON.stringify(withNap)});assert.equal(napSaved.status,200);
 const napEntry=(await get()).find(e=>e.day===day);assert.equal(napEntry.napMinutes,25);assert.equal(napEntry.napStartTime,'14:10');assert.equal(napEntry.napFeeling,3);assert.equal(napEntry.clarity,4);
 const noNap=await fetch(`${base}/api/entries`,{method:'PUT',headers,body:JSON.stringify({...withNap,napMinutes:0})});assert.equal(noNap.status,200);
 const noNapEntry=(await get()).find(e=>e.day===day);assert.equal(noNapEntry.napMinutes,0);assert.equal(noNapEntry.napStartTime,null);assert.equal(noNapEntry.napFeeling,null);
 const unauthorized=await fetch(`${base}/api/entries?day=${day}`,{method:'DELETE'});assert.equal(unauthorized.status,401);
 const deleted=await fetch(`${base}/api/entries?day=${day}`,{method:'DELETE',headers});assert.equal(deleted.status,200);wrote=false;
 assert.equal((await get()).length,before.length);
 const locked=await fetch(`${base}/api/session`,{method:'DELETE',headers});assert.equal(locked.status,200);assert.ok(locked.headers.get('set-cookie').includes('Max-Age=0'));
 console.log('PASS: independent password access, wrong password / forged session rejection, HTTP-only session, origin rejection, validation, durable CRUD, protected delete, lock, cleanup.');
}finally{if(wrote)await fetch(`${base}/api/entries?day=${day}`,{method:'DELETE',headers});}
